### ISSUE TITLE
Feature Request : adding it in Detectron2

### ISSUE THREAD

**Issue by Cyril9227** [rwightman/efficientdet-pytorch#1]
Thank you very much for your project, really looking into it. It would be awesome to integrate it within Detectron2 pipeline as current FPN implementation is super slow.

**Comment by Kevin-Delnoije** [comment]
I think integrating is a great a idea aswell, since you get a lot of functionality for free like:
-dataloaders
-training and test code
-visualization
-anchor generation

the only thing required if i am not mistaken would be to register effnet+bifpn as backbone and use that in the retinanet meta-architure. (or a slightly modified one)
the weights  of the prediction head probably need to be retrained though, not sure if that is a problem.

I have some spare time next week so i hope i can make a pull request!

**Comment by hiyyg** [comment]
+1 for this. Any update?

**Comment by rwightman** [comment]
@hiyyg at this point, doubt I'll do it. I've looked at it a few times but just too much work for limited gain. Given how slow / unlikely they are to add 3rd party code, it'd probably end up a lonely fork that I have to maintain against their changes. 

I kind of like the fact that this is stand alone, fairly compact. With openimages dataset I support more obj detection datasets now.
