### ISSUE TITLE
'NestedTensor' object has no attribute 'size'

### ISSUE THREAD

**Issue by Aliweka2020** [rwightman/efficientdet-pytorch#252]
I am trying to use efficientnet bacbone with DETR but get this error

  File "C:\Users\Ali\AppData\Local\Continuum\anaconda3\lib\site-packages\timm\models\layers\padding.py", line 32, in pad_same
    ih, iw = x.size()[-2:]
AttributeError: 'NestedTensor' object has no attribute 'size'

I searched for NestedTensor to unpack to get the dimension but useless.

Could anyone help?!

**Comment by rwightman** [comment]
I'm going to move this to discussions since it isn't a bug.

The workound @arekmula provided if you're using a training setup that uses lists or tuples is correct, the 'bench' wrappers for training here expect tensors. Another approach would be to write an alternate Train/Predict bench wrapper (https://github.com/rwightman/efficientdet-pytorch/blob/master/effdet/bench.py#L79)  that accept sequences. ie DetBenchTrainSeq / DetBenchPredictSeq ... and modify the factory create fn to accept 'train_seq' and 'predict_seq' as the bench type. I'd accept a PR for that.

For nested tensor, I haven't spent much time with it, but since it's out of PyTorch tree it's not a high priority for me to support but likely can be supported with a similar approach as above (specific bench wrappers).
