### ISSUE TITLE
Error loading saved model checkpoints file during validation on custom test dataset

### ISSUE THREAD

**Issue by NeelBhowmik** [rwightman/efficientdet-pytorch#33]
Hi,
Thank you for the code repo. 
I am training on my custom dataset (5 class). The training is completed successfully (_tf_efficientdet_d1_). I am using single gpu for training/testing. 
Whilst evaluating on test set using _**validate.py**_, its raising below error to load the checkpoints model weight.

`bench = create_model(
        args.model,
        bench_task='predict',
        pretrained=args.pretrained,
        redundant_bias=args.redundant_bias,
        checkpoint_path=args.checkpoint,
        checkpoint_ema=args.use_ema,
    )`

`RuntimeError: Error(s) in loading state_dict for EfficientDet:
	Missing key(s) in state_dict: "fpn.resample.3.conv.conv.bias", `

Is it related to saving the model, using _nn.DataParallel_, or something else? 

Many thanks,
Neel

**Comment by rwightman** [comment]
It's the `redundant_bias` setting, it's a bit confusing sorry. I noticed that the TF models have unecessary biases, most convs have bias enabled followed by a BN with a bias, this is unecessary. So my train script defaulted to creating the models without the redudant bias because that's how i was trying to train new models, but validation had it enabled by default for compatibility with the TF weights. It'll be changed so that all tf_ models will stay as redudant_bias=True and all non tf_ models wiill have it disabled. 

In the meantime, toggle that setting and it should load the weights.

**Comment by NeelBhowmik** [comment]
Thanks for your suggestion. It works.

In the similar context of Custom dataset, do you recommend some parameters tuning/setting to start with during training? Although I know, it depends on the data I am using. In general, if the dataset size not large: ~15k images/ ~5 classes.

Thanks,
Neel

**Comment by rwightman** [comment]
If your custom dataset was somewhere in the COCO to ImageNet range of size, label quality, etc ... I'd start from the current cosine + momentum combo and tweak. However, for datasets that are smaller or quite a bit different from those, I think the best starting point is usualy adam or adamw with warmup + a plateau LR schedule w/ 10 or more patience epochs, LR starting somewhere between 1e-4 if you have few GPUS and small batch to 1e-3 or higher if you can manage big batches...

**Comment by glenn-jocher** [comment]
@rwightman this raises a good point. Do you usually scale LR with batch size, or do you scale loss with batch size? I used to think for SGD these were one and the same, but I recently realized the error of my ways, as in PyTorch weight decay scales more with the former than the latter.
