### ISSUE TITLE
AssertionError: APEX and CUDA required for fused optimizers

### ISSUE THREAD

**Issue by Naivepro1990** [rwightman/efficientdet-pytorch#46]
Hi,

I have four gpus and installed apex but still I am getting this error while trying to train using the training script given. Any suggestion to solve this problem.

**Comment by rwightman** [comment]
@Naivepro1990 you need to do a full apex install with C++ extensions for the fused optimizers to work, I assume there was an error in your build or you just did the python only install. It's also possible the apex removed one of the fused optimizers in my import from their master?

`pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./`

You need a working `nvcc` and libs installed for that, can be a bit of a pain. If that doesn't work you can just used `momentum` as the optimizer in the command line instead of `fusedmomentum`

**Comment by Naivepro1990** [comment]
As mentioned earlier, I used the command for installation and it worked fine. However, I still get the error. No idea why. For time being I will go with momentum.
