### ISSUE TITLE
Inference times

### ISSUE THREAD

**Issue by drwaltman** [rwightman/efficientdet-pytorch#59]
Hi, I have been looking into deploying EfficientDet and am curious about the performance of your implementation.  Have you benchmarked inference times, and are they comparable to the times listed on the TF2 Detection Model Zoo page? https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

Thanks for all the great work!

**Comment by rwightman** [comment]
@drwaltman I have not done the equivalent benchmarking, but I do know that single image inference times (and throughput) are not very fast, quite a bit of overhead. Large batched inference and training throughput on GPU are competitive with the original (this used to be quite a bit faster but the TF impl has been optimized quite a bit since release).

With ONNX -> TensorRT conversion and a platform specific post-processing impl I'm sure there is significant room for improvement over both the this code and the original TF, but that's likely only a funded goal for this codebase as it's of primary concern for embedded/mobile operation that's generally product focused.

**Comment by drwaltman** [comment]
@rwightman thanks for the quick response!  I have been looking into exporting a [pretrained model ](https://github.com/google/automl/tree/master/efficientdet#2-pretrained-efficientdet-checkpoints) to ONNX and converting to TensorRT for deploying with [NVIDIA's Triton Inference Server](https://github.com/NVIDIA/triton-inference-server).  Have you had any issues exporting to ONNX or converting to TensorRT?  I saw https://github.com/rwightman/efficientdet-pytorch/issues/32 and it looks like the export is possible.

**Comment by rwightman** [comment]
@drwaltman converting the whole predict bench with post-processing would be some work in my opinion, I think someone was successful or close to successful (with a few changes) just converting the model without post process and generate_detections
