### ISSUE TITLE
Training on Windows

### ISSUE THREAD

**Issue by pasandrei** [rwightman/efficientdet-pytorch#62]
Since there is no support for DistributedDataParallel on windows is there any way to use this repo without installing a linux based distro?

I tried to remove everything related to DDP, but a lot of work and carefulness is necessary.

**Comment by rwightman** [comment]
@pasandrei not sure why it wouldn't work single gpu, without using the distributed train script in Windows? unless torch distributed fails to even import, could just add an extra import guard and set DDP to None

**Comment by guitarmind** [comment]
Hi @rwightman , it turns out that the commit for this issue had broken the distributed GPU training on Linux machines.
I was seeing strange The given group does not exist errors from torch.distributed during the evaluation phase of training job.
After removing the changes of this commit targeting Windows environment, everything works now.

FYI and many thanks to your contribution of efficientdet-pytorch!
